services:
  fast-api:
    build: /api
    image: eoi-fastapi
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/code
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data